version: '3.8'
services:
  health-check-service:
    build: .
    image: martingrosek/health-check-service:latest  # Zamenjajte z vašim Docker Hub uporabniškim imenom
    ports:
      - "4005:4005"
    networks:
      - backend-network

networks:
  backend-network:
    external: true